#!/bin/bash
set -e

echo "== DEV-9 04: Generate DEV9_Workflows_Inventory.md =="

# 1) Ensure docs/dev directory exists
mkdir -p docs/dev

# 2) Write header for workflows inventory
cat <<'EOD' > docs/dev/DEV9_Workflows_Inventory.md
# DEV-9 Workflows Inventory

This document lists the current GitHub Actions workflows in `.github/workflows`
for the 1kUSD project and provides a short description slot for each workflow.

The list below was generated by DEV-9 AAAAAAAA as part of the CI hardening
preparation work. It should be kept up to date when workflows are added,
renamed or removed.
EOD

# 3) Append workflow list (if any)
if [ -d ".github/workflows" ]; then
  echo "" >> docs/dev/DEV9_Workflows_Inventory.md
  echo "## Workflow files" >> docs/dev/DEV9_Workflows_Inventory.md
  echo "" >> docs/dev/DEV9_Workflows_Inventory.md

  for f in .github/workflows/*.yml .github/workflows/*.yaml; do
    [ -e "$f" ] || continue
    name="$(basename "$f")"
    echo "- ${name} – TODO: description (DEV-9 / Architect)" >> docs/dev/DEV9_Workflows_Inventory.md
  done
else
  echo "" >> docs/dev/DEV9_Workflows_Inventory.md
  echo "_Note: .github/workflows directory not found at the time of this patch._" >> docs/dev/DEV9_Workflows_Inventory.md
fi

# 4) Log message
LOG_FILE="logs/project.log"
timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
echo "[DEV-9 04] ${timestamp} Added DEV9_Workflows_Inventory.md" >> "$LOG_FILE"

echo "== DEV-9 04 done =="
