name: Foundry CI (deterministic)

on:
  push:
    branches: [ "main", "dev12/**" ]
  pull_request: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: CI Setup (deterministic)
        run: bash scripts/ci_setup.sh

      - name: Run unit tests
        run: forge test -vv
