name: Docs Link Check (placeholder)
on:
  pull_request:
    paths:
      - "**/*.md"
  workflow_dispatch: {}
jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Placeholder link check
        run: |
          echo "Skipping real link check for now."
          echo "Config at tooling/LINKCHECK_CONFIG.json"
