name: Deploy Docs to GitHub Pages
on:
  push: { branches: [ main ] }
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Empfohlen für Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install MkDocs & theme
        run: |
          python -m pip install --upgrade pip
          python -m pip install mkdocs mkdocs-material

      # Debug: zeige Struktur
      - name: Show workspace
        run: |
          pwd
          ls -la
          echo "---- docs/ ----"
          (ls -la docs || true)
          echo "---- mkdocs.yml ----"
          sed -n '1,200p' mkdocs.yml

      # Sicherheitsnetz: index.md anlegen falls fehlt
      - name: Ensure docs/index.md exists
        run: |
          mkdir -p docs
          if [ ! -f docs/index.md ]; then
            echo "# 1kUSD Docs" > docs/index.md
          fi

      # Build ohne --strict (Warnungen ok)
      - name: Build site
        run: |
          python -m mkdocs --version
          python -m mkdocs build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
